name: Deploy to GCP Cloud Run

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # JDK version
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
        project_id: the-experience-270205  

    - name: Build and Push Docker Image
      run: |
        gcloud auth configure-docker
        docker build -t gcr.io/the-experience-270205/maven-app-image:${{ github.sha }} .
        docker push gcr.io/the-experience-270205/maven-app-image:${{ github.sha }}

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy maven-app-service --image gcr.io/the-experience-270205/helloworld:${{ github.sha }} --region us-central1 --platform managed --allow-unauthenticated
        # us-central1 is closest to Michigan

    # Optionally, add other steps like notifications or tests
