# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_URL: us.gcr.io/the-experience-270205/github-actions-repo/poc-spring-boot-cloud-run:${{ github.sha }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
        export_environment_variables: true

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: the-experience-270205
    - name: Use gcloud CLI
      run: gcloud info # Not requred, but can give you hints in the workflow if something goes wrong 
    
    - name: Configure docker
      run: gcloud auth configure-docker us.gcr.io

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 17
    
    - name: Build JAR
      run: mvn -B package --file pom.xml

    - name: Docker Build
      run: docker build -t $IMAGE_URL .
    - name: Docker Push
      run: docker push $IMAGE_URL

    - name: Update Cloud Run service
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: poc-spring-boot-cloud-run # same as the app in the $IMAGE_URL. Trigger
        image: ${{ env.IMAGE_URL }}
    
